import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:health/login_page.dart';
import 'firebase_options.dart'; // This should be generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Health App',
      home: LoginPage(),  // Ensure that LoginPage is defined
    );
  }
}